-- MySQL Script generated by MySQL Workbench
-- Sun May 21 02:14:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema actividad3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `actividad3` ;

-- -----------------------------------------------------
-- Schema actividad3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `actividad3` DEFAULT CHARACTER SET utf8 ;
USE `actividad3` ;

-- -----------------------------------------------------
-- Table `actividad3`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad3`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad3`.`produccion_diaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad3`.`produccion_diaria` (
  `id_produccion_diaria` INT NOT NULL AUTO_INCREMENT,
  `productos_id_producto` INT NOT NULL,
  `fecha` VARCHAR(30) NOT NULL,
  `cantidad_producida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_produccion_diaria`),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `actividad3`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produccion_diaria_productos1_idx` ON `actividad3`.`produccion_diaria` (`productos_id_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `actividad3`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad3`.`insumo` (
  `id_insumo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_insumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad3`.`recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad3`.`recetas` (
  `id_recetas` INT NOT NULL AUTO_INCREMENT,
  `insumo_id_insumo` INT NOT NULL,
  `productos_id_producto` INT NOT NULL,
  `cantidad_requerida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_recetas`),
  CONSTRAINT `fk_recetas_insumo`
    FOREIGN KEY (`insumo_id_insumo`)
    REFERENCES `actividad3`.`insumo` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recetas_productos1`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `actividad3`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_recetas_insumo_idx` ON `actividad3`.`recetas` (`insumo_id_insumo` ASC) VISIBLE;

CREATE INDEX `fk_recetas_productos1_idx` ON `actividad3`.`recetas` (`productos_id_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
